/*
 * Copyright 2024-2025 Embabel Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.embabel.impromptu.data;

import org.drivine.manager.PersistenceManager;
import org.drivine.query.QuerySpecification;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Exports Neo4j graph data to Cypher CREATE statements.
 * Uses Cypher string functions to build export statements server-side,
 * avoiding Drivine deserialization issues with nulls and arrays.
 */
@Service
public class GraphExportService {

    private static final Logger logger = LoggerFactory.getLogger(GraphExportService.class);
    private static final Path EXPORT_PATH = Path.of("data/exports/references.cypher");

    private final PersistenceManager persistenceManager;

    public GraphExportService(PersistenceManager persistenceManager) {
        this.persistenceManager = persistenceManager;
    }

    public record ExportResult(int nodes, int relationships, Path file) {}

    /**
     * Export all Reference nodes and their relationships to a Cypher file.
     */
    public ExportResult exportReferences() throws IOException {
        Files.createDirectories(EXPORT_PATH.getParent());

        // Get node count first
        Long nodeCount = persistenceManager.getOne(
                QuerySpecification.withStatement("MATCH (n:Reference) RETURN count(n) AS count")
                        .transform(Long.class)
        );

        // Get relationship count
        Long relCount = persistenceManager.getOne(
                QuerySpecification.withStatement("MATCH (:Reference)-[r]->(:Reference) RETURN count(r) AS count")
                        .transform(Long.class)
        );

        logger.info("Exporting {} nodes and {} relationships", nodeCount, relCount);

        try (var writer = new PrintWriter(new FileWriter(EXPORT_PATH.toFile()))) {
            writer.println("// Generated by Impromptu GraphExportService");
            writer.println("// Nodes: " + nodeCount + ", Relationships: " + relCount);
            writer.println();

            // Export nodes by type
            writer.println("// === COMPOSERS ===");
            exportComposers(writer);

            writer.println();
            writer.println("// === WORKS ===");
            exportWorks(writer);

            writer.println();
            writer.println("// === EPOCHS ===");
            exportEpochs(writer);

            writer.println();
            writer.println("// === GENRES ===");
            exportGenres(writer);

            writer.println();
            writer.println("// === RELATIONSHIPS ===");
            exportRelationships(writer);
        }

        logger.info("Exported to {}", EXPORT_PATH.toAbsolutePath());
        return new ExportResult(nodeCount.intValue(), relCount.intValue(), EXPORT_PATH);
    }

    private void exportComposers(PrintWriter writer) {
        // Build the CREATE statement entirely in Cypher to avoid deserialization issues
        var query = """
                MATCH (c:Composer)
                RETURN 'CREATE (:Composer:Reference {id: "' + c.id + '", name: "' +
                       REPLACE(REPLACE(c.name, '\\\\', '\\\\\\\\'), '"', '\\\\"') + '", completeName: ' +
                       CASE WHEN c.completeName IS NULL THEN 'null' ELSE '"' + REPLACE(REPLACE(c.completeName, '\\\\', '\\\\\\\\'), '"', '\\\\"') + '"' END +
                       ', birthYear: ' + COALESCE(toString(c.birthYear), 'null') +
                       ', deathYear: ' + COALESCE(toString(c.deathYear), 'null') +
                       ', description: ' + CASE WHEN c.description IS NULL THEN 'null' ELSE '"' + REPLACE(REPLACE(REPLACE(c.description, '\\\\', '\\\\\\\\'), '"', '\\\\"'), '\n', '\\\\n') + '"' END +
                       ', popular: ' + COALESCE(toString(c.popular), 'false') +
                       ', recommended: ' + COALESCE(toString(c.recommended), 'false') +
                       ', primarySource: ' + CASE WHEN c.primarySource IS NULL THEN 'null' ELSE '"' + c.primarySource + '"' END +
                       '});' AS line
                """;

        List<String> lines = persistenceManager.query(
                QuerySpecification.withStatement(query).transform(String.class)
        );

        lines.forEach(writer::println);
        logger.info("Exported {} composers", lines.size());
    }

    private void exportWorks(PrintWriter writer) {
        var query = """
                MATCH (w:Work)
                RETURN 'CREATE (:Work:Reference {id: "' + w.id + '", name: "' +
                       REPLACE(REPLACE(w.name, '\\\\', '\\\\\\\\'), '"', '\\\\"') + '", title: ' +
                       CASE WHEN w.title IS NULL THEN 'null' ELSE '"' + REPLACE(REPLACE(w.title, '\\\\', '\\\\\\\\'), '"', '\\\\"') + '"' END +
                       ', description: ' + CASE WHEN w.description IS NULL THEN 'null' ELSE '"' + REPLACE(REPLACE(REPLACE(w.description, '\\\\', '\\\\\\\\'), '"', '\\\\"'), '\n', '\\\\n') + '"' END +
                       ', popular: ' + COALESCE(toString(w.popular), 'false') +
                       ', recommended: ' + COALESCE(toString(w.recommended), 'false') +
                       ', primarySource: ' + CASE WHEN w.primarySource IS NULL THEN 'null' ELSE '"' + w.primarySource + '"' END +
                       '});' AS line
                """;

        List<String> lines = persistenceManager.query(
                QuerySpecification.withStatement(query).transform(String.class)
        );

        lines.forEach(writer::println);
        logger.info("Exported {} works", lines.size());
    }

    private void exportEpochs(PrintWriter writer) {
        var query = """
                MATCH (e:Epoch)
                RETURN 'CREATE (:Epoch:Reference {id: "' + e.id + '", name: "' +
                       REPLACE(REPLACE(e.name, '\\\\', '\\\\\\\\'), '"', '\\\\"') +
                       '", primarySource: ' + CASE WHEN e.primarySource IS NULL THEN 'null' ELSE '"' + e.primarySource + '"' END +
                       '});' AS line
                """;

        List<String> lines = persistenceManager.query(
                QuerySpecification.withStatement(query).transform(String.class)
        );

        lines.forEach(writer::println);
        logger.info("Exported {} epochs", lines.size());
    }

    private void exportGenres(PrintWriter writer) {
        var query = """
                MATCH (g:Genre)
                RETURN 'CREATE (:Genre:Reference {id: "' + g.id + '", name: "' +
                       REPLACE(REPLACE(g.name, '\\\\', '\\\\\\\\'), '"', '\\\\"') +
                       '", primarySource: ' + CASE WHEN g.primarySource IS NULL THEN 'null' ELSE '"' + g.primarySource + '"' END +
                       '});' AS line
                """;

        List<String> lines = persistenceManager.query(
                QuerySpecification.withStatement(query).transform(String.class)
        );

        lines.forEach(writer::println);
        logger.info("Exported {} genres", lines.size());
    }

    private void exportRelationships(PrintWriter writer) {
        // COMPOSED relationships
        var composedQuery = """
                MATCH (c:Composer)-[:COMPOSED]->(w:Work)
                RETURN 'MATCH (a {id: "' + c.id + '"}), (b {id: "' + w.id + '"}) CREATE (a)-[:COMPOSED]->(b);' AS line
                """;

        List<String> composed = persistenceManager.query(
                QuerySpecification.withStatement(composedQuery).transform(String.class)
        );
        composed.forEach(writer::println);
        logger.info("Exported {} COMPOSED relationships", composed.size());

        // OF_EPOCH relationships
        var epochQuery = """
                MATCH (c:Composer)-[:OF_EPOCH]->(e:Epoch)
                RETURN 'MATCH (a {id: "' + c.id + '"}), (b {id: "' + e.id + '"}) CREATE (a)-[:OF_EPOCH]->(b);' AS line
                """;

        List<String> epochs = persistenceManager.query(
                QuerySpecification.withStatement(epochQuery).transform(String.class)
        );
        epochs.forEach(writer::println);
        logger.info("Exported {} OF_EPOCH relationships", epochs.size());

        // INFLUENCED relationships
        var influencedQuery = """
                MATCH (a:Composer)-[r:INFLUENCED]->(b:Composer)
                RETURN 'MATCH (a {id: "' + a.id + '"}), (b {id: "' + b.id + '"}) CREATE (a)-[:INFLUENCED {' +
                       'reason: ' + CASE WHEN r.reason IS NULL THEN 'null' ELSE '"' + REPLACE(REPLACE(REPLACE(r.reason, '\\\\', '\\\\\\\\'), '"', '\\\\"'), '\n', '\\\\n') + '"' END +
                       ', strength: ' + COALESCE(toString(r.strength), 'null') +
                       ', confidence: ' + COALESCE(toString(r.confidence), 'null') +
                       ', divergence: ' + COALESCE(toString(r.divergence), 'null') +
                       '}]->(b);' AS line
                """;

        List<String> influenced = persistenceManager.query(
                QuerySpecification.withStatement(influencedQuery).transform(String.class)
        );
        influenced.forEach(writer::println);
        logger.info("Exported {} INFLUENCED relationships", influenced.size());
    }

    /**
     * Get the export file path.
     */
    public Path getExportPath() {
        return EXPORT_PATH;
    }
}
