// Generated by Impromptu GraphExportService
// Run: ./scripts/load_data.sh

// === CONSTRAINTS ===
CREATE CONSTRAINT composer_id IF NOT EXISTS FOR (c:Composer) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT work_id IF NOT EXISTS FOR (w:Work) REQUIRE w.id IS UNIQUE;
CREATE CONSTRAINT epoch_id IF NOT EXISTS FOR (e:Epoch) REQUIRE e.id IS UNIQUE;
CREATE CONSTRAINT genre_id IF NOT EXISTS FOR (g:Genre) REQUIRE g.id IS UNIQUE;

// === COMPOSERS ===
LOAD CSV WITH HEADERS FROM 'file:///composers.csv' AS row
CREATE (:Composer:Reference {
  id: row.id,
  name: row.name,
  completeName: CASE WHEN row.completeName = '' THEN null ELSE row.completeName END,
  birthYear: CASE WHEN row.birthYear = '' THEN null ELSE toInteger(row.birthYear) END,
  deathYear: CASE WHEN row.deathYear = '' THEN null ELSE toInteger(row.deathYear) END,
  description: CASE WHEN row.description = '' THEN null ELSE row.description END,
  popular: row.popular = 'true',
  recommended: row.recommended = 'true',
  primarySource: CASE WHEN row.primarySource = '' THEN null ELSE row.primarySource END
});

// === WORKS ===
LOAD CSV WITH HEADERS FROM 'file:///works.csv' AS row
CREATE (:Work:Reference {
  id: row.id,
  name: row.name,
  title: CASE WHEN row.title = '' THEN null ELSE row.title END,
  description: CASE WHEN row.description = '' THEN null ELSE row.description END,
  popular: row.popular = 'true',
  recommended: row.recommended = 'true',
  primarySource: CASE WHEN row.primarySource = '' THEN null ELSE row.primarySource END
});

// === EPOCHS ===
LOAD CSV WITH HEADERS FROM 'file:///epochs.csv' AS row
CREATE (:Epoch:Reference {
  id: row.id,
  name: row.name,
  primarySource: CASE WHEN row.primarySource = '' THEN null ELSE row.primarySource END
});

// === GENRES ===
LOAD CSV WITH HEADERS FROM 'file:///genres.csv' AS row
CREATE (:Genre:Reference {
  id: row.id,
  name: row.name,
  primarySource: CASE WHEN row.primarySource = '' THEN null ELSE row.primarySource END
});

// === COMPOSED RELATIONSHIPS ===
LOAD CSV WITH HEADERS FROM 'file:///composed_rels.csv' AS row
MATCH (c:Composer {id: row.composerId})
MATCH (w:Work {id: row.workId})
CREATE (c)-[:COMPOSED]->(w);

// === OF_EPOCH RELATIONSHIPS ===
LOAD CSV WITH HEADERS FROM 'file:///epoch_rels.csv' AS row
MATCH (c:Composer {id: row.composerId})
MATCH (e:Epoch {id: row.epochId})
CREATE (c)-[:OF_EPOCH]->(e);

// === OF_GENRE RELATIONSHIPS ===
LOAD CSV WITH HEADERS FROM 'file:///genre_rels.csv' AS row
MATCH (w:Work {id: row.workId})
MATCH (g:Genre {id: row.genreId})
CREATE (w)-[:OF_GENRE]->(g);
