/*
 * Copyright 2024-2025 Embabel Software, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.embabel.impromptu.vaadin.components;

import com.embabel.impromptu.data.GraphExportService;
import com.embabel.impromptu.data.influence.ComposerInfluenceLoader;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Hr;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.notification.NotificationVariant;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Panel for managing composer influence relationships.
 * Allows viewing stats, deleting all influences, and reimporting from CSV.
 */
public class InfluencesPanel extends VerticalLayout {

    private static final Logger logger = LoggerFactory.getLogger(InfluencesPanel.class);

    private final ComposerInfluenceLoader influenceLoader;
    private final GraphExportService exportService;
    private final Span relationshipCountSpan;
    private TextField csvPathField;

    public InfluencesPanel(ComposerInfluenceLoader influenceLoader, GraphExportService exportService) {
        this.influenceLoader = influenceLoader;
        this.exportService = exportService;

        setPadding(false);
        setSpacing(false);
        setSizeFull();

        // Stats row at top
        relationshipCountSpan = new Span("0");
        relationshipCountSpan.getStyle().set("font-weight", "500");

        var statsRow = new HorizontalLayout();
        statsRow.setWidthFull();
        statsRow.setPadding(true);
        statsRow.setSpacing(true);
        statsRow.setAlignItems(Alignment.CENTER);
        statsRow.add(createStatBadge("Relationships", relationshipCountSpan));

        // Description
        var description = new Div();
        description.getStyle()
                .set("padding", "var(--lumo-space-m)")
                .set("color", "var(--lumo-secondary-text-color)")
                .set("line-height", "1.5");
        description.setText("Composer influence relationships are generated by LLM and stored in a CSV file for musicologist review. " +
                "Approved relationships (status=approved) can be imported into Neo4j.");

        // Actions section
        var actionsSection = createActionsSection();

        add(statsRow, new Hr(), description, new Hr(), actionsSection);

        refresh();
    }

    private Div createStatBadge(String label, Span valueSpan) {
        var badge = new Div();
        badge.getStyle()
                .set("display", "flex")
                .set("align-items", "center")
                .set("gap", "var(--lumo-space-xs)")
                .set("padding", "var(--lumo-space-xs) var(--lumo-space-s)")
                .set("background", "var(--lumo-contrast-5pct)")
                .set("border-radius", "var(--lumo-border-radius-m)");

        var labelSpan = new Span(label + ":");
        labelSpan.getStyle().set("color", "var(--lumo-secondary-text-color)");

        badge.add(labelSpan, valueSpan);
        return badge;
    }

    private VerticalLayout createActionsSection() {
        var section = new VerticalLayout();
        section.setPadding(true);
        section.setSpacing(true);
        section.setWidth("100%");

        // CSV path field (prepopulated, read-only for display)
        csvPathField = new TextField("CSV File");
        csvPathField.setValue(influenceLoader.getCsvPath().toAbsolutePath().toString());
        csvPathField.setWidthFull();
        csvPathField.setReadOnly(true);
        csvPathField.getStyle().set("font-family", "monospace");

        // Import approved button
        var importButton = new Button("Import Approved", VaadinIcon.DOWNLOAD.create());
        importButton.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        importButton.addClickListener(e -> importInfluences(false));

        // Import ALL button (dangerous - includes unreviewed)
        var importAllButton = new Button("Import ALL", VaadinIcon.WARNING.create());
        importAllButton.addThemeVariants(ButtonVariant.LUMO_ERROR, ButtonVariant.LUMO_PRIMARY);
        importAllButton.getStyle()
                .set("background", "linear-gradient(135deg, #dc2626, #991b1b)")
                .set("font-weight", "bold");
        importAllButton.getElement().setAttribute("title", "Import ALL relationships including unreviewed - use with caution!");
        importAllButton.addClickListener(e -> importInfluences(true));

        // Delete all button
        var deleteButton = new Button("Delete All", VaadinIcon.TRASH.create());
        deleteButton.addThemeVariants(ButtonVariant.LUMO_ERROR);
        deleteButton.addClickListener(e -> deleteAllInfluences());

        // Export Cypher button
        var exportButton = new Button("Export Cypher", VaadinIcon.UPLOAD.create());
        exportButton.addThemeVariants(ButtonVariant.LUMO_CONTRAST);
        exportButton.addClickListener(e -> exportCypher());

        // Button rows
        var importRow = new HorizontalLayout(importButton, importAllButton, deleteButton);
        importRow.setSpacing(true);

        var exportRow = new HorizontalLayout(exportButton);
        exportRow.setSpacing(true);

        section.add(csvPathField, importRow, exportRow);
        return section;
    }

    private void importInfluences(boolean importAll) {
        var ui = getUI().orElse(null);

        new Thread(() -> {
            try {
                var result = importAll
                        ? influenceLoader.loadAll()
                        : influenceLoader.loadApproved();
                if (ui != null) {
                    ui.access(() -> {
                        var message = importAll
                                ? String.format("Imported ALL: %d relationships (%d skipped, %d not found)",
                                        result.loaded(), result.skipped(), result.notFound())
                                : String.format("Imported %d approved relationships (%d skipped, %d not found)",
                                        result.loaded(), result.skipped(), result.notFound());
                        Notification.show(message, 5000, Notification.Position.BOTTOM_CENTER)
                                .addThemeVariants(NotificationVariant.LUMO_SUCCESS);
                        refresh();
                    });
                }
            } catch (Exception e) {
                logger.error("Failed to import influences", e);
                if (ui != null) {
                    ui.access(() -> {
                        Notification.show("Error: " + e.getMessage(), 5000, Notification.Position.BOTTOM_CENTER)
                                .addThemeVariants(NotificationVariant.LUMO_ERROR);
                    });
                }
            }
        }).start();
    }

    private void deleteAllInfluences() {
        var ui = getUI().orElse(null);

        new Thread(() -> {
            try {
                var deleted = influenceLoader.deleteAllInfluences();
                if (ui != null) {
                    ui.access(() -> {
                        Notification.show("Deleted " + deleted + " relationships", 3000, Notification.Position.BOTTOM_CENTER)
                                .addThemeVariants(NotificationVariant.LUMO_SUCCESS);
                        refresh();
                    });
                }
            } catch (Exception e) {
                logger.error("Failed to delete influences", e);
                if (ui != null) {
                    ui.access(() -> {
                        Notification.show("Error: " + e.getMessage(), 5000, Notification.Position.BOTTOM_CENTER)
                                .addThemeVariants(NotificationVariant.LUMO_ERROR);
                    });
                }
            }
        }).start();
    }

    private void exportCypher() {
        var ui = getUI().orElse(null);

        new Thread(() -> {
            try {
                var result = exportService.exportReferences();
                if (ui != null) {
                    ui.access(() -> {
                        Notification.show(
                                String.format("Exported %d nodes, %d relationships to %s",
                                        result.nodes(), result.relationships(), result.file()),
                                5000, Notification.Position.BOTTOM_CENTER
                        ).addThemeVariants(NotificationVariant.LUMO_SUCCESS);
                    });
                }
            } catch (Exception e) {
                logger.error("Failed to export graph", e);
                if (ui != null) {
                    ui.access(() -> {
                        Notification.show("Error: " + e.getMessage(), 5000, Notification.Position.BOTTOM_CENTER)
                                .addThemeVariants(NotificationVariant.LUMO_ERROR);
                    });
                }
            }
        }).start();
    }

    public void refresh() {
        try {
            var count = influenceLoader.countInfluenceRelationships();
            var formatter = java.text.NumberFormat.getNumberInstance();
            relationshipCountSpan.setText(formatter.format(count));
        } catch (Exception e) {
            logger.warn("Failed to get influence count: {}", e.getMessage());
            relationshipCountSpan.setText("?");
        }
    }
}
